name: animated_flip_counter
description: An implicit animation widget that flips from one number to another, with support for customize styles, decimals and negative values.
version: 0.3.4
homepage: https://github.com/h65wang/flutter-animated-counter

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter

screenshots:
  - description: 'Animated flip counter (decimal)'
    path: 'gifs/percent.gif'
  - description: 'Animated flip counter (integer)'
    path: 'gifs/counter.gif'
  - description: 'Demo flip counter in an app'
    path: 'gifs/demo.gif'

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter: